# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIChallenge_DS.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(806, 559)
        Dialog.setStyleSheet("background-color: rgb(70, 199, 231);\n"
"background-color: rgb(17, 17, 67);\n"
"")
        Dialog.setModal(False)
        self.cbSelection = QtWidgets.QComboBox(Dialog)
        self.cbSelection.setGeometry(QtCore.QRect(30, 50, 301, 22))
        self.cbSelection.setStyleSheet("color: rgb(11, 11, 42);\n"
"background-color: rgb(219, 219, 231);")
        self.cbSelection.setObjectName("cbSelection")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.cbSelection.addItem("")
        self.lblTitle = QtWidgets.QLabel(Dialog)
        self.lblTitle.setGeometry(QtCore.QRect(30, 20, 161, 31))
        self.lblTitle.setStyleSheet("color: rgb(255, 242, 252);")
        self.lblTitle.setObjectName("lblTitle")
        self.btnExit = QtWidgets.QPushButton(Dialog)
        self.btnExit.setGeometry(QtCore.QRect(680, 20, 101, 23))
        self.btnExit.setStyleSheet("color: rgb(11, 11, 42);\n"
"background-color: rgb(181, 227, 67);")
        self.btnExit.setObjectName("btnExit")
        self.tblViewer = QtWidgets.QTableWidget(Dialog)
        self.tblViewer.setGeometry(QtCore.QRect(30, 110, 751, 431))
        self.tblViewer.setStyleSheet("color: rgb(11, 11, 42);\n"
"background-color: rgb(219, 219, 231);")
        self.tblViewer.setObjectName("tblViewer")
        self.tblViewer.setColumnCount(0)
        self.tblViewer.setRowCount(0)
        self.btnPlot = QtWidgets.QPushButton(Dialog)
        self.btnPlot.setGeometry(QtCore.QRect(680, 50, 101, 23))
        self.btnPlot.setStyleSheet("color: rgb(11, 11, 42);\n"
"background-color: rgb(181, 227, 67);")
        self.btnPlot.setObjectName("btnPlot")
        self.btnSelect = QtWidgets.QPushButton(Dialog)
        self.btnSelect.setGeometry(QtCore.QRect(360, 50, 101, 23))
        self.btnSelect.setStyleSheet("color: rgb(11, 11, 42);\n"
"background-color: rgb(181, 227, 67);")
        self.btnSelect.setObjectName("btnSelect")

        self.retranslateUi(Dialog)
        self.btnExit.clicked.connect(Dialog.exec)
        self.btnPlot.clicked.connect(Dialog.open)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cbSelection.setItemText(0, _translate("Dialog", "All items"))
        self.cbSelection.setItemText(1, _translate("Dialog", "Estructure data"))
        self.cbSelection.setItemText(2, _translate("Dialog", "Total visitors by state (month)"))
        self.cbSelection.setItemText(3, _translate("Dialog", "Total visitors by state (year)"))
        self.cbSelection.setItemText(4, _translate("Dialog", "Total visitors by kind of visitors per state"))
        self.cbSelection.setItemText(5, _translate("Dialog", "Total visitors by kind of visitors & state (month)"))
        self.cbSelection.setItemText(6, _translate("Dialog", "Total visitors by kind of visitors & state (year)"))
        self.cbSelection.setItemText(7, _translate("Dialog", "Total visitors by kind of work (month)"))
        self.cbSelection.setItemText(8, _translate("Dialog", "Total visitors by kind of work (year)"))
        self.cbSelection.setItemText(9, _translate("Dialog", "Total visitors by kind of work and kind of visitor (year)"))
        self.cbSelection.setItemText(10, _translate("Dialog", "Average of visitors by state (month)"))
        self.cbSelection.setItemText(11, _translate("Dialog", "Average of visitors by state (year)"))
        self.cbSelection.setItemText(12, _translate("Dialog", "Average of visitors by kind of visitors per state (month)"))
        self.cbSelection.setItemText(13, _translate("Dialog", "Average of visitors by kind of visitors per state (year)"))
        self.cbSelection.setItemText(14, _translate("Dialog", "Percent of visitors by place per state (month)"))
        self.cbSelection.setItemText(15, _translate("Dialog", "Percent of visitors by place per state (year)"))
        self.cbSelection.setItemText(16, _translate("Dialog", "Percent of visitors by kind of visitors (month)"))
        self.cbSelection.setItemText(17, _translate("Dialog", "Percent of visitors by kind of visitors (year)"))
        self.cbSelection.setItemText(18, _translate("Dialog", "Percent of visitors by kind of visitors per place (month)"))
        self.cbSelection.setItemText(19, _translate("Dialog", "Percent of visitors by kind of visitors per place (year)"))
        self.lblTitle.setText(_translate("Dialog", "Tables"))
        self.btnExit.setText(_translate("Dialog", "Exit"))
        self.btnPlot.setText(_translate("Dialog", "Plot"))
        self.btnSelect.setText(_translate("Dialog", "Select"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
